### ISSUE TITLE
Hyperbolic Activations

### ISSUE THREAD

**Issue by towermitten** [novak-99/MLPP#7]
In the README, it looks like you've (planned on) implemented a lot of hyperbolic functions as activation functions. 

If you don't mind me asking, are there specific cases where such functions with a diverging gradient (such as Cosh and Sinh) that you've implemented would be helpful? I am very curious, I haven't seen these used before. Thanks!

**Comment by novak-99** [comment]
Hi, thank you for bringing this up. The hyperbolic functions which I have listed in the Deep NN section of the readme are existing functions in the Activation class, which a user can call independently on some scalar, vector, or matrix. While you are incorrect in that they are not used very much in ML/DL, I decided to include them as possible activations in ANNs because I have found that in some small scale cases, say the XOR dataset, they can work quite well in conjunction with the sigmoid function, and just wanted to leave the option to use them available for users.
